const images = {
  // shadow_bottom: require("./shadow_bottom.png"),
  ic_cloud: require('./ic_cloud.png'),
  ic_avatar: require('./ic_avatar.png'),
  // ic_remove: require("./ic_remove.png"),
  // ic_search: require("./ic_search.png"),
  // ic_logo: require("./ic_logo.png"),
  // ic_stripe: require("./stripe.png"),
  // ic_menu: require("./ic_menu.png"),
  ic_calendar: require('./ic_calendar.png'),
  bg_bt_check_in: require('./bg_bt_check_in.png'),
  bg_bt_request_late: require('./bg_bt_request_late.png'),
  bg_bt_custom: require('./bg_bt_custom.png'),
  bg_bt_wfh: require('./bg_bt_wfh.png'),
  bg_bt_onsite: require('./bg_bt_onsite.png'),
  ic_check_in: require('./ic_check_in.png'),
  // ic_request_late: require("./ic_request_late.png"),
  // ic_rmis: require("./ic_rmis.png"),
  ic_ba: require('./ic_ba.png'),
  ic_eleaning: require('./ic_eleaning.png'),
  ic_etms: require('./ic_etms.png'),
  // ic_jira: require("./ic_jira.png"),
  ic_edu: require('./ic_edu.png'),
  // ic_note: require("./ic_note.png"),
  // ic_wave_hand: require("./ic_wave_hand.png"),
  // ic_wifi: require("./ic_wifi.png"),
  // ic_no_wifi: require("./ic_no_wifi.png"),
  // ic_news: require("./ic_news.png"),
  ic_add: require('./ic_add.png'),
  // ic_wfh: require("./ic_wfh.png"),
  // ic_onsite: require("./ic_onsite.png"),
  ic_email: require('./ic_email.png'),
  ic_erev: require('./ic_erev.png'),
  ic_bank: require('./ic_bank.png'),
  ic_ad: require('./ic_ad.png'),
  // ic_smp: require("./ic_smp.png"),
  // ic_work_place: require("./ic_work_place.png"),
  ic_fis_lib: require('./ic_fis_lib.png'),
  ic_epms: require('./ic_epms.png'),
  // ic_okr: require("./ic_okr.png"),
  ic_doc_hr: require('./ic_doc_hr.png'),
  ic_decentralization: require('./ic_decentralization.png'),
  // ic_survey: require("./ic_survey.png"),
  ic_crm: require('./ic_crm.png'),
  ic_soft_hr: require('./ic_decentralization.png'),
  ic_dms: require('./ic_dms.png'),
  ic_conflu: require('./ic_conflu.png'),
  ic_eiso: require('./ic_eiso.png'),
  ic_epayment: require('./ic_epayment.png'),
  ic_epucharse: require('./ic_epucharse.png'),
  ic_empty: require('./ic_empty.png'),
  // ic_tems: require("./ic_tems.png"),
  // ic_work_chat: require("./ic_work_chat.png"),
  // ic_no_class: require("./ic_no_class.png"),
  // ic_logo_fpt: require("./logo_fpt.png"),
  ic_chung_ta: require('./ic_chung_ta.png'),
  ic_fpt_software: require('./ic_fpt_software.png'),
  ic_fpt_edu: require('./ic_fpt_edu.png'),
  ic_fpt_is: require('./ic_fpt_is.png'),
  ic_fpt_shop: require('./ic_fpt_shop.png'),
  ic_fpt_telecom: require('./ic_fpt_telecom.png'),
  // ic_logojgp: require('./logo.jpg'),
  // ic_tech_insight: require("./ic_tech_insight.png"),
  ic_fpt: require('./ic_fpt.png'),
  // ic_fpt_synnex: require("./ic_fpt_synnex.png"),
  // swipe: require("./swipe.png"),
  // swipe2: require("./swipe2.png"),
  // swipe3: require("./swipe3.png"),
  name_check_history: 'calendar-check',
  reload: 'redo-alt',
  name_back: 'chevron-left',
  name_check: 'check',
  name_wifi: 'wifi',
  name_none_wifi: 'wifi-slash',
  name_calendar: 'calendar-alt',
  name_note: 'exclamation-triangle',
  name_bell: 'bell',
  name_sign_out: 'sign-out-alt',
  name_file: 'file-alt',
  name_device: 'mobile-alt',
  otherWeb: 'globe-americas',

  name_request: 'clipboard-check',
  name_create_request: 'edit',
  name_attendance_records: 'user-edit',
  name_wave_hand: 'mitten',
  name_attendance_edu: 'address-card',
  name_show_pass: 'eye',
  name_hide_pass: 'eye-slash',
  name_info: 'info-circle',
  ic_fis: require('./ic_fis.png'),
};
export default images;
